ENV['RNLLAMA_BUILD_FROM_SOURCE'] = '1'
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OfflineInterviewApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'OfflineInterviewAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |config_name, config_file|
        toolchain_swift = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/${PLATFORM_NAME}'
        config_file.attributes['LIBRARY_SEARCH_PATHS'] ||= '$(inherited)'
        unless config_file.attributes['LIBRARY_SEARCH_PATHS'].include?(toolchain_swift)
          config_file.attributes['LIBRARY_SEARCH_PATHS'] = "#{config_file.attributes['LIBRARY_SEARCH_PATHS']} \"#{toolchain_swift}\""
          config_file.save_as(Pathname.new(File.join(installer.config.project_pods_root, target.xcconfig_relative_path(config_name))))
        end
      end
    end
  end
end
